### ISSUE TITLE
Feature: Better server system (more commands and more...)

### ISSUE THREAD

**Issue by mrrpmrreeoow** [AlphaVerUnofficialJars/LilypadServer#2]
### Which component should be improved?

Gameplay

### Describe your suggestion

It would be good not to be just commands like `/ban` and `/kick`, but something like `/npc` (npc system with commands), more worlds (and world swithing command), repeated chat messages for everyone - server notifications, `/vanish` command, Rank system - owner rank, admin rank etc ... , and also features from #1, moderation system (`/mute`, `/warn`, etc...) and other important elements of public server.

**Comment by Smaedd** [comment]
A lot of these commands are out of scope, as I want to keep the server as vanilla-feeling as possible. The changes I'm planning to add, while they do change functionality, will in the best-case scenario present no difference to what would be average vanilla lilypad server gameplay. As a result, actions like `/npc` and `/vanish` don't really fit where I'm looking to go with this specific server.
